# Not using Travis anymore but keeping this for now.

arch: 
  - arm64
dist: bionic
language: c
sudo: false
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  apt:
    update: true
    packages:
    - texinfo
    - openjdk-8-jdk-headless
    - dos2unix
    - unrar-free
    - g++
cache:
  directories:
  - build
  - toolchain/work
jobs:
  include:
  - stage: clean
    script:
      - make clean
  - stage: Build toolchain
    script:
      - make toolchain_clean
      - cd toolchain && make setup
      - pwd
      - ls
      - ls ./toolchain
      - ls ./toolchain/binutils-2.34
      - HOST=aarch64-linux-gnu make build-binutils
      - HOST=aarch64-linux-gnu make build-gcc-1
      - HOST=aarch64-linux-gnu make build-newlib
      - HOST=aarch64-linux-gnu make build-gcc-2
      - HOST=aarch64-linux-gnu make build-ldscripts
      - cd .. && make tools_clean tools_build
      - export GENDEV=`pwd`/build
      - make sgdk_clean sgdk_build
      - make sgdk_samples
  - stage: release to github
    if: tag IS present
    script:
    - echo "Deploying to github..."
    - VER=$TRAVIS_TAG make release
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      file_glob: true
      file:
        - dist/gendev_*.txz
        - dist/gendev_*_all.deb
      on:
        tags: true
        repo: kubilus1/gendev
