#!/bin/sh

echo "Post install"
echo "export GENDEV=/opt/toolchains/gen" > ~/.gendev
echo "export PATH=\$GENDEV/m68k-elf/bin:\$GENDEV/bin:\$PATH" >> ~/.gendev
echo "export GENDEV=/opt/toolchains/gen" > ~/.32xdev
echo "export PATH=\$GENDEV/sh-elf/bin:\$GENDEV/m68k-elf/bin:\$GENDEV/bin:\$PATH" >> ~/.32xdev
